feat: добавить изменения по ТЗ спринта 10
max-vassiliev/java-filmorate pull request #2
Opened 2022-11-20 23:18 UTC by max-vassiliev

**Финальный проект спринта 10 (Версия 1)**

Новая функциональность:
1. добавление и удаление из друзей;
2. возможность поставить и отозвать лайк;
3. получение списка популярных фильмов.

Рефакторинг:
1. добавлено внедрение зависимостей;
2. валидация выведена в отдельный класс-сервис ValidationService;
3. хранение данных выведено в отдельные классы в пакете storage;
4. добавлен единый контроллер ErrorHandler для обработки исключений.

2022-11-21 09:34 UTC, AnastasiyaFomkina requested changes
Вот [отличная статья](https://habr.com/ru/company/piter/blog/676394/) про `lombok`. В коммерческой разработке сейчас уже почти никто не пишет стандартный боллер-плейт(геттеры, сеттеры, конструкторы и подобное), так как `lombok` делает это за разработчика, плюс код становится короче и более читаемым

2022-11-21 09:34 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +    public ErrorResponse ValidationException(final ValidationException e) {
Переименуй, пожалуйста, все однобуквенные переменные. Они делают код менее читаемым

2022-11-21 09:34 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    @Autowired
`Опционально`
Так как мы используем `lombok` в приложении, проще будет доверить инжект полей ему:
https://www.baeldung.com/spring-injection-lombok

2022-11-21 09:34 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmNotFoundException.java
> +    public FilmNotFoundException() {
Если нам нужен конструктор без параметров, то лучше генерировать его с помощью аннотации `lombok`:
`@NoArgsConstructor`

2022-11-21 09:34 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/exception/IncorrectParameterException.java
> +    public String getParameter() {
Для создания геттера лучше использовать аннотацию `@Getter` от `lombok`

2022-11-21 09:34 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/exception/IncorrectParameterException.java
> +    public IncorrectParameterException(String parameter) {
А здесь лучше подойдет аннотация `@RequiredArgsConstructor`

2022-11-21 09:34 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/exception/UserNotFoundException.java
> +    public UserNotFoundException() {
`@NoArgsConstructor`

2022-11-21 09:34 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +    public String getError() {
`@Getter`

2022-11-21 09:34 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Integer> friends = new HashSet<>();
👍

2022-11-21 09:34 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Integer> likes = new HashSet<>();
👍

2022-11-21 09:34 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private int compareLikes(Film film1, Film film2) {
Лучше не использовать цифры в именовании переменных, так код сложнее читать
```suggestion
    private int compareLikes(Film film, Film filmToCompare) {
```

2022-11-21 09:34 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidationService.java
> +        if (user.getEmail() == null) {
Лучше добавить полям аннотацию `@NotNull` из пакета `javax.validation.constraints`. Тогда проверка сгенерируется автоматически и не будет занимать лишнее место :)

2022-11-22 17:56 UTC, max-vassiliev commented on src/main/java/ru/yandex/practicum/filmorate/exception/IncorrectParameterException.java
> +    public String getParameter() {
Поставил аннотацию @Getter, но потом обнаружил, что этот класс нигде не используется, поэтому я его удалил.

2022-11-22 17:57 UTC, max-vassiliev commented on src/main/java/ru/yandex/practicum/filmorate/exception/IncorrectParameterException.java
> +    public IncorrectParameterException(String parameter) {
После этой аннотации обнаружил, что класс нигде не используется, поэтому я его удалил.

2022-11-22 18:14 UTC, max-vassiliev commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidationService.java
> +        if (user.getEmail() == null) {
Удалил лишние проверки. Насчет аннотации — у меня уже стоит `@NotBlank`. Я так понял из [документации](https://docs.jboss.org/hibernate/beanvalidation/spec/2.0/api/javax/validation/constraints/package-summary.html), что `@NotBlank` включает проверку на null и что поэтому дополнительно аннотацию `@NotNull` ставить не нужно. Надеюсь, так можно :)

2022-11-23 07:44 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidationService.java
> +        if (user.getEmail() == null) {
Тогда можно оставить только `@NotBlank`.

2022-11-23 07:54 UTC, AnastasiyaFomkina approved these changes

2022-11-23 16:52 UTC, merged